server.port=8081

# RabbitMQ Connection Settings
# Defines where the RabbitMQ server is running (Local Docker instance)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Custom Messaging Properties
# Names for the Exchange and Routing Key used to route order messages
rabbitmq.exchange.name=order.exchange
rabbitmq.routing.key=order.created.key