# Run Payment Service on Port 8082
server.port=8082

# RabbitMQ Connection Settings
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Custom Messaging Properties
rabbitmq.queue.name=payment.queue
rabbitmq.exchange.name=order.exchange
rabbitmq.routing.key=order.created.key